from setuptools import setup, find_packages

setup(
    name="akavesdk",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "grpcio>=1.60.0",
        "protobuf>=4.25.1",
        "google-api-python-client>=2.108.0",
        "google-auth>=2.23.0",
        "google-auth-oauthlib>=1.1.0",
        "google-auth-httplib2>=0.1.1",
        "google-cloud-storage>=2.13.0",
        "google-cloud-core>=2.4.1",
        "google-cloud-bigquery>=3.12.0",
        "google-cloud-bigquery-storage>=2.22.0",
        "google-cloud-bigtable>=2.19.0",
        "google-cloud-datastore>=2.15.0",
        "google-cloud-firestore>=2.13.0",
        "google-cloud-pubsub>=2.18.4",
        "google-cloud-spanner>=3.36.0",
        "google-cloud-logging>=3.8.0",
        "google-cloud-monitoring>=2.15.0",
        "google-cloud-trace>=1.10.0",
        "google-cloud-error-reporting>=1.6.0",
        "google-cloud-profiler>=3.4.0",
        "google-cloud-debugger>=3.1.0",
        "google-cloud-vision>=3.4.5",
        "google-cloud-language>=2.9.0",
        "google-cloud-translate>=3.11.0",
        "google-cloud-speech>=2.21.0",
        "google-cloud-texttospeech>=2.14.0",
        "google-cloud-videointelligence>=2.11.0",
        "google-cloud-dlp>=3.12.0",
        "google-cloud-kms>=2.15.0",
        "google-cloud-iam>=2.12.0",
        "google-cloud-resource-manager>=1.10.0",
        "google-cloud-scheduler>=2.12.0",
        "google-cloud-tasks>=2.14.0",
        "google-cloud-functions>=1.12.0",
        "google-cloud-run>=0.7.0",
        "google-cloud-appengine-admin>=1.10.0",
        "google-cloud-compute>=1.12.0",
        "google-cloud-dns>=0.35.0",
        "google-cloud-container>=2.20.0",
        "google-cloud-iam-logging>=1.2.0",
        "google-cloud-iam-credentials>=1.1.0",
        "google-cloud-iam-policy>=1.6.0",
        "google-cloud-iam-admin>=1.0.0",
        "google-cloud-iam-v1>=0.1.0",
        "google-cloud-iam-v2>=0.1.0",
        "google-cloud-iam-v2beta1>=0.1.0",
        "google-cloud-iam-v2beta2>=0.1.0",
        "google-cloud-iam-v2beta3>=0.1.0",
        "google-cloud-iam-v2beta4>=0.1.0",
        "google-cloud-iam-v2beta5>=0.1.0",
        "google-cloud-iam-v2beta6>=0.1.0",
        "google-cloud-iam-v2beta7>=0.1.0",
        "google-cloud-iam-v2beta8>=0.1.0",
        "google-cloud-iam-v2beta9>=0.1.0",
        "google-cloud-iam-v2beta10>=0.1.0",
    ],
    author="Your Name",
    author_email="your.email@example.com",
    description="Akave SDK for Python",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/akavesdk-py",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.7",
)
